name: Mods Update Release

on:
  push:
    paths:
      - 'mods/**'  # Trigger workflow when any changes happen in the mods folder

permissions:
  contents: write  # Explicitly allow write access to the contents (needed for creating releases)

jobs:
  release-modpack:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set Time Zone, Extract Commit Hash, and Record Changes
      - name: Set Time Zone, Extract Commit Hash, and Record Changes
        id: record_changes
        run: |
          export TZ="Europe/Warsaw"
          
          # Get the short commit hash
          commit_hash=$(git rev-parse --short HEAD)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

          # Capture changes (added, modified, deleted files) in the mods folder
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            git diff --name-status HEAD^ HEAD mods/ > changes.txt
          else
            # Fall back to capturing all changes in mods if no previous commit exists
            git diff --name-status -- mods/ > changes.txt
          fi

          # Debug output to check what changes were captured
          echo "Contents of changes.txt:"
          cat changes.txt
          echo "changes=$(cat changes.txt)" >> $GITHUB_ENV

      # Step 3: Define Timestamp and Zip the Mods Directory
      - name: Zip Mods Directory
        run: |
          export TZ="Europe/Warsaw"
          timestamp=$(date +"%d.%m.%Y")
          echo "timestamp=$timestamp" >> $GITHUB_ENV
          zip -r -3 mods_$timestamp.zip mods

      # Step 4: Create a Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release-${{ env.timestamp }}-${{ env.commit_hash }}"
          release_name: "Mods Update - ${{ env.timestamp }} - ${{ env.commit_hash }}"
          draft: false
          prerelease: false
          body: |
            I ❤️ Kanye West

            Changes in this release:
            ${{ env.changes }}

      # Step 5: Upload the Zipped Mods Archive
      - name: Upload Mods Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url
